Fix backports.tarfile vendored requirement
conda-forge/setuptools-feedstock pull request #352
Opened 2024-07-22 08:29 UTC by duncanmmacleod

This PR fixes #351 by adding an explicit requirement on a vendored package that cannot be imported from the `setuptools._vendor` namespace on Python 3.8.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

2024-07-22 08:34 UTC, duncanmmacleod commented
The linter doesn't like it, but I'm not what what else to suggest as a fix (other than 'drop python 3.8').

2024-07-22 09:02 UTC, rgommers requested changes
I don't think this can be correct. `setuptools` by design does not have any external dependencies, they're all vendored. There's an in-tree `backports.tarfile` at https://github.com/pypa/setuptools/tree/main/setuptools/_vendor/backports/tarfile, if that doesn't work then it's a bug in `setuptools` that must be fixed upstream.

2024-07-22 09:34 UTC, rgommers commented
> the issue is with the conda package `backports`, which is a namespace hack.

I'm not sure I understand. Could you elaborate on what the hack is? It sounds like you're saying that the same packages installed into a virtualenv do work, but something is off with either conda's support for namespace packages, or with https://github.com/conda-forge/backports-feedstock specifically?

2024-07-22 09:46 UTC, duncanmmacleod commented
> It sounds like you're saying that the same packages installed into a virtualenv do work,

This is true, virtualenvs ***do*** work:

```console
$ python3.8 -m venv ./venv
$ ./venv/bin/python3 -m pip install backports.zoneinfo setuptools==71.0.4
$ ./venv/bin/python3 -c "import setuptools; import backports.zoneinfo; print(backports); import backports.tarfile; print(backports.tarfile)"
<module 'backports' from '/home/duncan/tmp/venv/lib/python3.8/site-packages/backports/__init__.py'>
<module 'backports.tarfile' from '/home/duncan/tmp/venv/lib/python3.8/site-packages/setuptools/_vendor/backports/tarfile/__init__.py'>
```

> but something is off with either conda's support for namespace packages, or with https://github.com/conda-forge/backports-feedstock specifically?

Yes. the `backports` conda package (and only the conda package) provides an ***empty*** `backports/__init__.py` file, which means that the Python importer doesn't know that it is the base of a namespace package, which means any attempt to import `backports.*` will only resolve to `.../site-packages/backports/` (I think).

In a virtualenv, for comparison, the `.../site-packages/backports/__init__.py` includes the appropriate `pkgutil` namespace package declaration:

```python
$ cat ./venv/lib/python3.8/site-packages/backports/__init__.py
# A Python "namespace package" http://www.python.org/dev/peps/pep-0382/
# This always goes inside of a namespace package's __init__.py
from pkgutil import extend_path

__path__ = extend_path(__path__, __name__)  # type: ignore
```

This matches the declaration from the `.../site-packages/setuptools/_vendor/backports/__init__.py` file:

```python
$ cat ./venv/lib/python3.8/site-packages/setuptools/_vendor/backports/__init__.py
__path__ = __import__('pkgutil').extend_path(__path__, __name__)  # type: ignore
```

I suppose the fix would then be to ensure the the backports ***conda*** package does this.

2024-07-22 10:02 UTC, duncanmmacleod commented
I have posted an upstream issue here: https://github.com/conda-forge/backports-feedstock/issues/6 and will post a PR to fix it shortly.

2024-07-22 10:02 UTC, closed without merging

2024-07-22 10:05 UTC, rgommers commented
Thanks! I agree that fixing `backports-feedstock` is the better fix here.

2024-07-25 14:43 UTC, jaraco commented
> I don't think this can be correct. `setuptools` by design does not have any external dependencies, they're all vendored.

For clarity, Setuptools is aiming to properly declare its dependencies. With the release of Setuptools 71, it _prefers_ that the dependencies be available in the environment, superseding the vendored ones, with the ultimate aim of removing the vendored ones entirely (assuming a solution to https://github.com/pypa/packaging-problems/issues/342 is feasible) or at least limiting the use of vendored dependencies to the most narrow use-cases. Right now, Setuptools is in a transitional state where the "core" (required) dependencies are declared in an extra (`setuptools[core]`). IMHO, downstream packagers such as setuptools-feedstock _should_ use this signal to include the declared dependencies (if possible).

> Thanks! I agree that fixing `backports-feedstock` is the better fix here.

I'm also good with this approach, as it's compatible with Setuptools' use of namespace packages and the spec for backports.

2024-07-25 16:46 UTC, rgommers commented
> Setuptools is aiming to properly declare its dependencies. With the release of Setuptools 71, it _prefers_ that the dependencies be available in the environment,

Thanks for pointing that out @jaraco! I completely missed that change -and it is good to hear.

I think we should do both then: finish the `backports` namespace fix _and_ declare the dependency as `setuptools` now prefers. @duncanmmacleod would you agree?